# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(default=None)),
                ('author_username', models.CharField(default=None, max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField(max_length=1000)),
                ('content', models.TextField()),
                ('url_media', models.URLField()),
                ('publicated_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('BOR', 'Borrador'), ('PUB', 'Publicado')], default='PUB', max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='Categories.Category')),
            ],
        ),
    ]
